### ISSUE TITLE
Allow integrer scaling

### ISSUE THREAD

**Issue by myself600** [deathkiller/jazz2-native#4]
The default renderer uses non-square pixels, which looks bad

### Jazz² Resurrection @1920x1080:
![jazz2-resurrection](https://user-images.githubusercontent.com/3542623/194908160-281bae8e-4c46-4a18-8bd5-29e7257e8594.gif)

### Original cropped to 16:9 @1920x1080:
![jazz2-cropped](https://user-images.githubusercontent.com/3542623/194900897-6447748e-5af6-4009-a9a6-cd8a9072f4cf.gif)

### Enlarged:
![a](https://user-images.githubusercontent.com/3542623/194911003-737cde89-1f5b-450a-9a45-df88999d55cf.gif)
![b](https://user-images.githubusercontent.com/3542623/194911007-54b6f316-7810-4d3f-9b66-2d57bf3109e4.gif)

**Edit:** Completely reworded my request

**Comment by deathkiller** [comment]
I use full HD resolution and it looks exactly the same as #2, but you are right if I resize the window it could cause distorted image like in picture #1. I will try to implement integer scaling as you propose.

**Comment by deathkiller** [comment]
I implemented it according to your description (before edit). But I see your GPU rasterizes it differently than mine. I don't see the lines caused by misaligned tiles. What's your GPU?

Here is result:
**Disabled:**
![image](https://user-images.githubusercontent.com/884052/194929872-dbc2483c-7e9e-442a-8488-6a11a2f7d295.png)
**Enabled:**
![image](https://user-images.githubusercontent.com/884052/194929907-e1a7c57a-5c7b-47bb-b75a-1d70f94bff45.png)

**Comment by myself600** [comment]
Ahh, sorry. I realized after posting the issue that the game doesn't need 1:1 scaling, so filtering is probably unnecessary. Rendering on your pictures looks good, so the issue is very likely my GPU driver rendering the game incorrectly (including tiles showing [white dots](https://user-images.githubusercontent.com/3542623/194961381-fea9ce4a-94d4-4008-9c54-6495713d4db6.gif) and a [slightly different color palette](https://user-images.githubusercontent.com/3542623/194962211-556f65b8-f9c2-4fb5-8c32-0fe73a4601b5.gif)). My GPU is a Mali-T860 MP4 (Pinebook Pro) running via Panfrost, which supports OpenGL ES 3.1 and no Vulkan atm.

I've tried to build 12da2e3 with the following error:

> /var/tmp/pamac-build-pbpro/jazz2-git/src/jazz2-native/Jazz2/Jazz2/UI/UpscaleRenderPass.cpp:16:76: error: cannot convert ‘float*’ to ‘double*’
   16 |                         float widthFrac = modf((float)targetWidth / width, &widthRatio);
      |                                                                            ^~~~~~~~~~~
      |                                                                            |
      |                                                                            float*

...
> /var/tmp/pamac-build-pbpro/jazz2-git/src/jazz2-native/Jazz2/Jazz2/UI/UpscaleRenderPass.cpp:17:79: error: cannot convert ‘float*’ to ‘double*’
   17 |                         float heightFrac = modf((float)targetHeight / height, &heightRatio);
      |                                                                               ^~~~~~~~~~~~
      |                                                                               |
      |                                                                               float*

[jazz2_build.log.gz](https://github.com/deathkiller/jazz2-native/files/9748723/jazz2_build.log.gz) (.7z actually)

**Comment by myself600** [comment]
Basically, I would like to force the game to output square pixels without filtering and see if it would fix the problem for me

**Comment by deathkiller** [comment]
I fixed the errors and also renamed it to "Antialiasing" (because it looks better but also a bit blurry when active). Slightly different color palette is probably because Jazz² Resurrection loads palettes and then renders it differently than original JJ2 which uses software rendering, not GPU. 

To fix misaligned tiles, you can try to adjust `texBiasX` and `texBiasY` here - https://github.com/deathkiller/jazz2-native/blob/master/Jazz2/Jazz2/Tiles/TileMap.cpp#L510-L542
For example, you can try to add `0.5f` or something like that and it could fix the issue, but it's a lot of experimenting.

**Comment by myself600** [comment]
This is how it should look like when working correctly:

![jazz2-antialiasing](https://user-images.githubusercontent.com/3542623/195328026-669dc0fa-800c-4624-9fbd-a299c4ecfd5b.gif)

I've tried it in windowed mode since that doesn't produce in-game artifacts, but it doesn't seem to work for me at all (the resolution still appears jerky at arbitrary resolutions when the rendering artifacts are not present). Forcing square pixels should resolve this issue however, hence why I'm reopening my request (integrer scaling, i.e. no filtering).

**Comment by deathkiller** [comment]
And this is how it looks on my PC in Jazz² Resurrection:
**Disabled:**
![image](https://user-images.githubusercontent.com/884052/195444733-d802891d-3661-4a72-bb1d-2577e7345234.png)
**Enabled:**
![image](https://user-images.githubusercontent.com/884052/195444763-6216a91d-6909-4584-8e8f-bc9bb55e085f.png)
I don't know how to fix something that looks good for me. I don't know how to "force square pixels", I see pixels are already square.

**Comment by myself600** [comment]
Fair enough. The idea is to avoid the need for filtering, which would be optimal while also less resource hungry. It also looks like anti-aliasing works properly.

**Comment by deathkiller** [comment]
The only solution I can think of would be to calculate viewport resolution from target resolution, so it can be multiplied back to target with integer. But it would be additional work and it would not look good for all resolutions.
